package mice;

/**
 *
 * @author Jacinto
 */
public class Startmeny extends javax.swing.JFrame {

    public Startmeny() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnÖppnaFönsterLäggTillAllt = new javax.swing.JButton();
        btnÖppnaFönsterVisaAllt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnÖppnaFönsterLäggTillAllt.setText("Lägg till/Uppdatera");
        btnÖppnaFönsterLäggTillAllt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnÖppnaFönsterLäggTillAlltMouseClicked(evt);
            }
        });

        btnÖppnaFönsterVisaAllt.setText("Visa");
        btnÖppnaFönsterVisaAllt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnÖppnaFönsterVisaAlltMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnÖppnaFönsterLäggTillAllt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(btnÖppnaFönsterVisaAllt)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btnÖppnaFönsterLäggTillAllt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnÖppnaFönsterVisaAllt)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * När användaren klickar på knappen så instansieras objektet "LäggTillAllt".
     * @param evt 
     */
    private void btnÖppnaFönsterLäggTillAlltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnÖppnaFönsterLäggTillAlltMouseClicked
        LäggTillAllt öppnaFönsterLäggTill = new LäggTillAllt();
        öppnaFönsterLäggTill.setVisible(true);
    }//GEN-LAST:event_btnÖppnaFönsterLäggTillAlltMouseClicked

    /**
     * När användaren klickar på knappen så instansieras objektet "VisaAllt"
     * @param evt 
     */
    private void btnÖppnaFönsterVisaAlltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnÖppnaFönsterVisaAlltMouseClicked
        VisaAllt öppnaFönsterVisaAllt = new VisaAllt();
        öppnaFönsterVisaAllt.setVisible(true);
    }//GEN-LAST:event_btnÖppnaFönsterVisaAlltMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startmeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startmeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startmeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startmeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startmeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnÖppnaFönsterLäggTillAllt;
    private javax.swing.JButton btnÖppnaFönsterVisaAllt;
    // End of variables declaration//GEN-END:variables
}
