/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mice;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import static mice.LäggTillAllt.pathway;
import se.oru.informatik.InformatikDB;
import se.oru.informatik.InformatikException;

public class VisaKompetensDomän extends javax.swing.JFrame {

private InformatikDB idb;
private static String rubrikNamn;
    
    public VisaKompetensDomän(String rubrikNamn) {
        initComponents();
        
        this.rubrikNamn=rubrikNamn; // Det värde användaren valt i comboBoxen i det föregående fönstret "VisaAllt".
        
         try
        {
            idb = new InformatikDB(pathway());
        }
        catch(InformatikException e)
                {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
         setRubrik();
         setBeskrivning();
         setAnstalldaComboBox();
    }
    
   public static String pathway()
   {
   String path = System.getProperty("user.dir") + "//MICEDB.FDB";
   
   return path;
   
   }
    
    /**
     * Metoden tar fältet rubrikNamn och sätter JLabeln, som ska agera
     * rubrik för detta fönster, med fältets värde.
     */
    
    private void setRubrik()
    {
        lblRubrik.setText(rubrikNamn);
    }

    
    /**
     * Metoden hämtar alla värden från kolumnen "beskrivning", från tabellen "Kompetensdoman", 
     * som är på samma rad som fältet "rubrikNamn" i tabellen. Detta hämtas från databasen och sätts
     * sedan in i den textarea som visar beskrivningen. Textarean sätts som oredigerbar.
     */
    private void setBeskrivning()
    {
        String sqlFraga = "select beskrivning from KOMPETENSDOMAN where benamning = '"+rubrikNamn+"'";
        try
        {
            
         String rubrik = idb.fetchSingle(sqlFraga);
         txtABeskrivning.setText(rubrik);
         txtABeskrivning.setEditable(false);
    }
    catch (InformatikException e)
    {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }
    
   /**
    * Metoden hämtar alla värden från kolumnen "namn" från tabellen "Anstalld"
    * som matchar de AIDn som finns i tabellen "Har_kompetens" som finns 
    * på samma rad som "rubrikNamn". Ifall några värden faktiskt hämtas så
    * raderas alla befintliga värden i den angivna comboBoxen där användaren kan se anställda
    * samt att värdena sätts in i en lokal ArrayList. Därefter körs en for-loop
    * som hämtar alla indexvärden i arraylistan och sätter in dessa i den angivna
    * comboBoxen där användaren kan se anställda.
    */
    private void setAnstalldaComboBox()
    {
        String sqlFraga = "SELECT namn from anstalld\n" +
"join HAR_KOMPETENS on anstalld.aid=HAR_KOMPETENS.aid\n" +
"join KOMPETENSDOMAN on KOMPETENSDOMAN.KID=HAR_KOMPETENS.KID\n" +
"where benamning = '"+rubrikNamn+"'";
        try
    {
        ArrayList<String> anstalldaLista = idb.fetchColumn(sqlFraga);
        
        if(!(anstalldaLista.isEmpty()))
        {
            cbAnstallda.removeAllItems();
            for(int i=0; i < anstalldaLista.size(); i++)
            {
                
                    cbAnstallda.addItem(anstalldaLista.get(i));
            }
        }
    }
    catch (InformatikException e)
    {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtABeskrivning = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cbAnstallda = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblRubrik.setText("jLabel1");

        txtABeskrivning.setColumns(20);
        txtABeskrivning.setRows(5);
        jScrollPane1.setViewportView(txtABeskrivning);

        jLabel1.setText("Beskrivning:");

        cbAnstallda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inga anställda" }));

        jLabel2.setText("Anställda med kompetens för denna domän:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblRubrik))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAnstallda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRubrik)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAnstallda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaKompetensDomän.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaKompetensDomän.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaKompetensDomän.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaKompetensDomän.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaKompetensDomän(rubrikNamn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAnstallda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JTextArea txtABeskrivning;
    // End of variables declaration//GEN-END:variables
}
